services:
  webapp:
    command: sh -c "npm i && npm run dev -- --host"
    restart: on-failure
    working_dir: /webapp
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 3000:5173
      - 24678:24678
    volumes:
      - ./webapp:/webapp
      - /webapp/node_modules

  game-api:
    command: sh -c "run --watch --allow-net src/main.ts"
    restart: on-failure
    build:
      context: ./game-api-2
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./game-api-2:/app
