FROM node:18.16-alpine as build
WORKDIR /webapp
COPY package.json package-lock.json ./
RUN npm i
COPY . .
RUN npm run build

FROM node:18.16-alpine as deploy
WORKDIR /webapp
COPY --from=build /webapp/package*.json .
RUN npm ci --omit=dev
COPY --from=build /webapp/build .
CMD [ "node", "index.js" ]
